project/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^project/', include('project.foo.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'views.home', name='home'),
    url(r'^search/$','views.search'),
    url(r'^contact/', 'views.contact'),
    url(r'^about/', 'views.about'),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^tinymce/filebrowser/',include('filebrowser.urls')),
    url(r'^uploadify/', include('uploadify.urls')),
)

project/svarobor/models.py
from django.db import models
from django.contrib.auth.models import User

U_CHOICES = (
    ('2', '220'),
    ('3', '380'),

)

YESNO_CHOICES = (
    ('Y', u'Да'),
    ('N', u'Нет'),

)

class TechHarakteristiki(models.Model):
    tovar = models.OneToOneField('spravochnik.Nomenklatura')
    tok_min = models.IntegerField(blank=True, null=True)
    tok_max = models.IntegerField(blank=True, null=True)
    period_nagruzki = models.IntegerField(blank=True, null=True)
    mind_elektroda = models.DecimalField(max_digits=2, decimal_places=1,blank=True,null=True, help_text=u'Минимальный диаметр электрода, мм')
    maxd_elektroda = models.IntegerField(blank=True, null=True, help_text=u'Максимальный диаметр электрода, мм')
    max_mochnost = models.DecimalField(max_digits=5, decimal_places=2, blank=True,null=True)
    u = models.CharField(max_length=1, choices=U_CHOICES, default='2', help_text=u'Напряжение, В')
    u_dugi = models.IntegerField(blank=True, null=True, help_text=u'Напряжение дуги')
    delta_u = models.CharField(max_length=20, blank=True, help_text=u'Допустимое отклонение напряжения')
    chastota_seti = models.CharField(max_length=10, blank=True)
    kpd = models.DecimalField(max_digits=2, decimal_places=0,blank=True,null=True)
#    kolichestvo_postov
    gabarity = models.CharField(max_length=20, blank=True)
    ves = models.DecimalField(max_digits=2, decimal_places=1,blank=True,null=True)
    ves_brutto  = models.DecimalField(max_digits=2, decimal_places=1,blank=True,null=True)
    trehfaznoe_u = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Трехфазное питание, В')
    anti_stick = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Антиприлипание')
    hot_start = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Поджиг дуги')
    arc_force = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Регулировка силы дуги')
    zachita_napryajeniya = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Защита от перепадов напряжения')
    zachita_razbyzgiv = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Защита от разбрызгивания')
    vozdushnoe_ohlagdenie = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Воздушное охлаждение')
    klas_zaschity = models.CharField(max_length=10, blank=True)

    def __unicode__(self):
        return u'%s' % (self.tovar)
        


class DopInfo(models.Model):
    strana_proiz = models.ForeignKey('spravochnik.Strana', blank=True, help_text=u'В какой стране изготовлено')
    cena = models.DecimalField(max_digits=11, decimal_places=2,blank=True,null=True)
    cena_opt = models.DecimalField(max_digits=11, decimal_places=2,blank=True,null=True)

    def __unicode__(self):
        return u'%s' % (self.cena)
        

class DopKomplekt(models.Model):
    sumka = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text = u'Наличие кейса')
    maska = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text = u'Маска сварщика')
    schetka = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Щетка')
    zazhim_zemli = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Зажим заземления')
    derzhatel_elektr = models.CharField(max_length=1, choices=YESNO_CHOICES, default='N', help_text=u'Держатель электродов')

    def __unicode__(self):
        return u'%s' % (self.maska)
        
class Prodaja(models.Model):
    author = models.ForeignKey(User)
    prodavec = models.ForeignKey('spravochnik.Contragent')
    nomenklatura = models.ForeignKey('spravochnik.Nomenklatura')
    dop_info = models.OneToOneField(DopInfo)
    dop_komplekt = models.OneToOneField(DopKomplekt, blank=True, null=True)
    
    def __unicode__(self):
        return u'%s' % (self.prodavec)

project/templates/about.html
{% extends "base.html" %}
{% block title %}О нас. Сварочный{% endblock %}


{% block leftmenu %}
{%endblock %}

{% block caption%}
    <h1>О нас</h1>
{% endblock %}

{% block content %}
<fieldset>

<p>Если у вас есть вопросы или предложения, <a href="/contact/">НАПИШИТЕ НАМ</a></p>

<p>www.svarochnyy.ru</p>

</fieldset>
{% endblock %}

project/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="ru">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">


<meta name="keywords" content="
{% block meta-keywords %}
    {% for object in PROIZVODITEL %}
        {{ object.name }}
    {% endfor %}
{% endblock %}
" />
<meta name="description" content="
{% block meta-description %}
    {% for object in PROIZVODITEL %}
        {{ object.name }}
    {% endfor %}
{% endblock %}" />
{% block extra-head %}{% endblock %}
{% block google-analytics %}{% endblock %}

</head>
<body>
    <link rel="stylesheet" href="/media/css/style.css">
    <title>{% block title %}Заголовок{% endblock %}</title>
    
    <div id="headbanner">
    </div>
    
    <div id="header">
        {% block header %}
            
            <div id="search">
                {% block search%}
                    <form action="/search/" method="get">
                        <label for="q">Найти</label>
                        <input name="q" type="text">
                        <input value="Поиск" type="submit">
                    </form>
                {% endblock %}
            </div>
        {% endblock %}
    </div>

        <div id="horizont_menu">
            <div id="horizont_menuelements">
                <div class="start_topmenu">
                {% block horizontmenu%}
                    <ul>
                        <li><a id="start_topmenu_activeloc" href="/">Главная</a></li>
                        <li><a href="/about/">О нас</a></li>
                        <li><a href="/contact/">Задать вопрос</a></li>
                    </ul>
                {%endblock %}
                </div>
                <div class="start_submenu">
                {% block horizontsubmenu%}
                        <ul>
                        {% for object in PROIZVODITEL %}
                            <li><a href="/catalog/proizvoditel/{{ object.slug }}/">{{ object.name }}</a></li>
                        {% endfor %}
                        </ul>
                {% endblock%}
                </div>
                    
            </div>
        </div>

<div id="dannie">
    <div id="leftmenu">
        {% block leftmenu %}
        <div class="leftmenu_inner">
        <h3>Каталог</h3>
        </div>
        {% endblock %}
    </div>
    <div id="caption">
        {% block caption%}
        {% endblock %}
    </div>
    <div id="main">
        {% block content %}
            Содержимое
        {% endblock %}
    </div>
    <div id="content_wrap"></div>
</div>
<div id="footer">
        {% block footer %}
        
 
        {% endblock %}<br><br>

        
</div>

</body></html>

project/templates/category.html
{% extends "base.html" %}

{% block title %}Сварочный инвертор, полуавтомат, генератор{% endblock %}



{% block leftmenu %}

<h3>Каталог</h3>
    <div class="leftmenu_inner">
    {{category}}
    
    {% if proizvoditel_list %}
        <ul id="menu_ul">
        {% for object in proizvoditel_list %}
            <li><a href="{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Нет производителей для данной категории</p>
    {% endif %}
    </div>    
    
{% endblock %}

{% block caption%}
<h1>{{category}}</h1>
{% endblock %}

{% block content %}
Для {{category.name}} есть производители:
{% for object in proizvoditel_list %}
    <li><a href="{{ object.slug }}/">{{ object.name }}</a></li>
{% endfor %}

В категории {{category.name}} есть товары:
{% for object in tovar_list %}
    <li><a href="/catalog/tovar/{{ object.slug }}/">{{ object.name }}</a></li>
{% endfor %}

{% endblock %}

project/templates/category_proizvoditel.html
{% extends "base.html" %}

{% block title %}Сварочный инвертор, полуавтомат, генератор{% endblock %}



{% block leftmenu %}

<h3>Каталог</h3>
    <div class="leftmenu_inner">
    {{category}}
    
    {% if proizvoditel_list %}
        <ul id="menu_ul">
        {% for object in proizvoditel_list %}
            <li><a href="/catalog/proizvoditel/{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Нет производителей для данной категории</p>
    {% endif %}
    </div>    
    
{% endblock %}

{% block caption%}
<h1>{{category}}/{{proizvoditel}}</h1>
{% endblock %}

{% block content %}
Для {{category.name}} есть производители:
{% for object in proizvoditel_list %}
    <li><a href="/catalog/proizvoditel/{{ object.slug }}/">{{ object.name }}</a></li>
{% endfor %}

Для {{category.name}} и {{proizvoditel}} есть товары:
{% for object in tovar_list %}
    <li><a href="/catalog/tovar/{{ object.slug }}/">{{ object.name }}</a></li>
{% endfor %}

{% endblock %}

project/templates/contact_form.html
{% extends "base.html" %}
{% block google-analytics %}
{% endblock %}

{% block title %}Контакты. Сварочный{% endblock %}


{% block leftmenu %}
{% endblock %}

{% block content %}

<h1>
    Напишите нам сообщение
</h1>

<form action="/contact/" method="post">
    <fieldset>
  {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.subject.errors }}
        <label for="id_subject">Тема:</label>
        {{ form.subject }}

        {{ form.message.errors }}
        <label for="id_message">Ваше сообщение:</label>
        
        {{ form.message }}
        
        {{ form.sender.errors }}
        <label for="id_sender">Ваш e-mail адрес:</label>
        {{ form.sender }}

    </div>
    </fieldset>
    <p><input type="submit" value="Отправить сообщение" /></p>
</form>

{% endblock %}
{% block footer %}
{% endblock %}

project/templates/home.html
{% extends "base.html" %}

{% block title %}Сварочный инвертор, полуавтомат, генератор{% endblock %}


{% block leftmenu %}

    <div class="leftmenu_inner">
    <h3>Каталог</h3>
    <fieldset>
    <h4>Производители</h4>
        <ul id="menu_ul">
        {% for object in PROIZVODITEL %}
            <li><a href="/catalog/proizvoditel/{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    </fieldset>
    
    {% if category_list %}
    <fieldset>
    <h4>Категории</h4>
        <ul id="menu_ul">
        {% for object in category_list %}
            <li><a href="/catalog/category/{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>нет категорий в каталоге</p>
    {% endif %}
    </fieldset>
    </div>    
    
{% endblock %}

{% block caption%}
<h1>Сварочное оборудование</h1>
{% endblock %}

{% block content %}

    {% if tovar %}

    <h3>Новые товары</h3>
    <fieldset>
        {% for item in tovar %}
            <div id="catalog_item">                
                <a href="/catalog/tovar/{{ item.slug }}/">
                    {% if item.photo %}
                        <img src="{{item.photo.url}}" alt="{{item.category}} {{item.name}}"></br>
                    {% else %}
                        <img src="/media/images/nofoto.png" alt="{{item.category}} {{item.name}}"></br>
                    {% endif %}
                <span>{{item}}</span><br>
                {% if item.cena %}
                    Цена: {{item.cena}} руб.
                {% else %}
                    Цена не указана
                {% endif %}
                </a>
            </div>
        {% endfor %}
    </fieldset>
    {% endif %}
<br>
    <fieldset>
    <b>Производители</b><br>
    {% for object in PROIZVODITEL %}
        <a href="/catalog/proizvoditel/{{ object.slug }}/">{{ object.name }}   </a>  
    {% endfor %}
    </fieldset>
    
    <fieldset>
    <b>Категории</b><br>
    {% if category_list %}
        {% for object in category_list %}
            <a href="/catalog/category/{{ object.slug }}/">{{ object.name }}   </a>
        {% endfor %}
    {% else %}
        <p>нет категорий в каталоге</p>
    {% endif %}
    </fieldset>

{% endblock %}

project/templates/proizvoditel.html
{% extends "base.html" %}

{% block title %}Сварочный инвертор, полуавтомат, генератор{% endblock %}



{% block leftmenu %}
<h3>Каталог</h3>

    <div class="leftmenu_inner">
    <h3><a href="/catalog/proizvoditel/{{proizvoditel.slug}}">{{ proizvoditel }}</a></h3>
        {%if category_list %}
        <ul id="menu_ul">
            {% for object in category_list %}
                <li><a href="/catalog/proizvoditel/{{proizvoditel}}/{{ object.slug }}/">{{ object.name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>Нет доступных категорий</p>
        {% endif %}
    <h5>Другие производители</h5>
    <fieldset>
        <ul id="menu_ul">
        {% for object in PROIZVODITEL %}
            <li><a href="/catalog/proizvoditel/{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    </fieldset>
    </div>    
    
{% endblock %}

{% block caption%}
<h1>{{proizvoditel}}</h1>
{% endblock %}

{% block content %}

Для <a href="/catalog/proizvoditel/{{proizvoditel.slug}}">{{ proizvoditel }}</a> доступны следующие категории: 
    {% for object in category_list %}
        <li><a href="/catalog/proizvoditel/{{proizvoditel}}/{{ object.slug }}/">{{ object.name }}</a></li>
    {% endfor %}
У производителя {{proizvoditel.name}} есть товары:
{% for object in tovar_list %}
    <li><a href="/catalog/tovar/{{ object.slug }}/">{{ object.name }}</a></li>
{% endfor %}

{% endblock %}

project/templates/prozvoditel_category.html
{% extends "base.html" %}

{% block title %}{{proizvoditel}}/{{category}}{% endblock %}



{% block leftmenu %}

    <div class="leftmenu_inner">
    <h3>Производители</h3>
        <ul id="menu_ul">
        {% for object in PROIZVODITEL %}
            <li><a href="/catalog/proizvoditel/{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    
    <h3>Каталог</h3>
    {% if categorylist %}
        <ul id="menu_ul">
        {% for object in categorylist %}
            <li><a href="{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>нет категорий в каталоге</p>
    {% endif %}
    </div>    
    
{% endblock %}

{% block caption%}
<h1><a href="/catalog/proizvoditel/{{proizvoditel.slug}}">{{ proizvoditel }}</a>/<a href="/catalog/proizvoditel/{{proizvoditel.slug}}/{{ category.slug }}/">{{category}}</a></h1>
{% endblock %}

{% block content %}
Для <a href="/catalog/proizvoditel/{{proizvoditel.slug}}">{{ proizvoditel.name }}</a> доступны следующие категории: 
    {% for object in category_list %}
        <li><a href="/catalog/proizvoditel/{{proizvoditel.slug}}/{{ object.slug }}/">{{ object.name }}</a></li>
    {% endfor %}
У производителя {{proizvoditel.name}} в категории {{category}} есть товары:
{% for object in tovar_list %}
    <li><a href="/catalog/tovar/{{ object.slug }}/">{{ object.name }}</a></li>
{% endfor %}
{% endblock %}

project/templates/search.html
{% extends "base.html" %}

{% block title %}Результаты поиска{% endblock %}

{% block content %}
    <h1>
        Результаты по поиску: {{query}}
    </h1>

{% if error%}
    Ошибка: {{ error }}
{% endif %}
    
{% if search_list %}
    <ol>
    {% for tovar in search_list.object_list %}
        <li><a href="/catalog/tovar/{{ tovar.slug }}/">{{ tovar }}</a> </li>
    {% endfor %}
    </ol>

    <div class="pagination">
        <span class="step-links">
            {% if search_list.has_previous %}
                <a href="?page={{ search_list.previous_page_number }}">Предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ search_list.number }} из {{ search_list.paginator.num_pages }}.
            </span>

            {% if search_list.has_next %}
                <a href="?page={{ search_list.next_page_number }}">Следующая</a>
            {% endif %}
        </span>
    </div>

{% else %}
    <p>По вашему запросу ничего не найдено</p>
{% endif %}



{% endblock %}

project/templates/thanks.html
{% extends "shop/index.html" %}

{% block title %}Thanks{% endblock %}

{% block content %}

    <h1>Cпасибо за отправленное сообщение</h1>

{% endblock %}

project/templates/tovar_detail.html
{% extends "base.html" %}

{% block title %}{{tovar.name}}{% endblock %}



{% block leftmenu %}

    <div class="leftmenu_inner">
    <h3>Производители</h3>
        <ul id="menu_ul">
        {% for object in PROIZVODITEL %}
            <li><a href="/catalog/proizvoditel/{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    
    <h3>Каталог</h3>
    {% if categorylist %}
        <ul id="menu_ul">
        {% for object in categorylist %}
            <li><a href="{{ object.slug }}/">{{ object.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>нет категорий в каталоге</p>
    {% endif %}
    </div>    
    
{% endblock %}

{% block caption%}

<a href="/catalog/proizvoditel/{{tovar.proizvoditel.slug}}">{{ tovar.proizvoditel }}</a>/<a href="/catalog/proizvoditel/{{tovar.proizvoditel.slug}}/{{ tovar.category.slug }}/">{{tovar.category}}</a>
<h1>{{tovar}}</h1>
{% endblock %}

{% block content %}
<fieldset>
    {% if tovar %}
    <br>
            <a href="/catalog/tovar/{{ tovar.slug }}/">{{tovar.category}} {{tovar.name}}</a>
            <p>Производитель: <a href="/catalog/proizvoditel/{{tovar.proizvoditel.slug}}">{{ tovar.proizvoditel }}</a></p>
            {%if tovar.strana_brenda %}<p>Страна бренда: {{tovar.strana_brenda}}</p>{%endif%}
            {% if tovar.cena %}
                <p>Розничная цена: {{tovar.cena}} руб.</p>
            {% else %}
                <p>Цена не указана. Возможно цена есть в прайс-листе. Так же Вы можете уточнить цену написав нам сообщение в <a href="/contact/">ФОРМЕ</a> или по электронной почте</p>
            {% endif %}

            {% if tovar.photo %}
                <p><a href="{{tovar.photo.url}}"><img src="{{tovar.photo.url}}" alt="{{tovar.category}}{{tovar.name}}" height="100px"></a> <br>нажмите на фото для увеличения</p>
            {% else %}
                <p><img src="/media/images/nofoto.png" alt="{{tovar.category}}{{tovar}}" height="100px"></p>
            {% endif %}
            
            <b>Описание {{tovar}} </b>
            <fieldset>{{tovar.about|safe}}</fieldset>
            
            {% if tovar.techharakteristiki %}
            <b>Технические характеристики {{tovar}}</b>
            <fieldset>
            {% if tovar.techharakteristiki.get_u_display %}
            <p>Напряжение: {{tovar.techharakteristiki.get_u_display}} В </p>
            {% endif %}
            {% if tovar.techharakteristiki.tok_min %}
            <p>Ток минимальный: {{tovar.techharakteristiki.tok_min}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.tok_max %}
            <p>Ток максимальный: {{tovar.techharakteristiki.tok_max}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.period_nagruzki %}
            <p>Период нагрузки: {{tovar.techharakteristiki.period_nagruzki}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.mind_elektroda %}
            <p>Минимальный диаметр электрода, мм :{{tovar.techharakteristiki.mind_elektroda}} </p>
            {% endif %}
            {% if tovar.techharakteristiki.maxd_elektroda %}
            <p>Максимальный диаметр электрода, мм :{{tovar.techharakteristiki.maxd_elektroda}} </p>
            {% endif %}
            {% if tovar.techharakteristiki.max_mochnost %}
            <p>Максимальная мощность: {{tovar.techharakteristiki.max_mochnost}} </p>
            {% endif %}
            {% if tovar.techharakteristiki.u_dugi %}
            <p>Напряжение дуги: {{tovar.techharakteristiki.u_dugi}} </p>
            {% endif %}
            {% if tovar.techharakteristiki.delta_u %}
            <p>Допустимое отклонение напряжения: {{tovar.techharakteristiki.delta_u}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.chastota_seti %}
            <p>Частота сети: {{tovar.techharakteristiki.chastota_seti}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.kpd %}
            <p>КПД: {{tovar.techharakteristiki.kpd}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.kolichestvo_postov %}
            <p>Количество постов: {{tovar.techharakteristiki.kolichestvo_postov}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.gabarity %}
            <p>Габариты: {{tovar.techharakteristiki.gabarity}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.ves %}
            <p>Вес: {{tovar.techharakteristiki.ves}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.ves_brutto %}
            <p>Вес брутто: {{tovar.techharakteristiki.ves_brutto}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.trehfaznoe_u %}
            <p>Трехфазное питание: {{tovar.techharakteristiki.get_trehfaznoe_u_display}} </p>
            {% endif %}
            {% if tovar.techharakteristiki.anti_stick %}
            <p>Антиприлипание: {{tovar.techharakteristiki.get_anti_stick_display}} </p>
            {% endif %}
            {% if tovar.techharakteristiki.hot_start %}
            <p>Поджиг дуги: {{tovar.techharakteristiki.get_hot_start_display}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.arc_force %}
            <p>Регулировка силы дуги: {{tovar.techharakteristiki.get_arc_force_display}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.zachita_napryajeniya %}
            <p>Защита от перепадов напряжения: {{tovar.techharakteristiki.get_zachita_napryajeniya_display}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.zachita_razbyzgiv %}
            <p>Защита от разбрызгивания: {{tovar.techharakteristiki.get_zachita_razbyzgiv_display}}</p>
            {% endif %}
            {% if tovar.techharakteristiki.vozdushnoe_ohlagdenie %}
            <p>Воздушное охлаждение: {{tovar.techharakteristiki.get_vozdushnoe_ohlagdenie_display}} </p>
            {% endif %}
            {% if tovar.techharakteristiki.klas_zaschity %}
            <p>Класс защиты: {{tovar.techharakteristiki.klas_zaschity }}</p>
            {% endif %}
            </fieldset>
            {% endif %}
            
    {% else %}
        <p>Товар на оформлении</p>
    {% endif %}
        
</fieldset>

{% endblock %}